name: API Fetch Demo

on: [workflow_dispatch]   # Manually trigger the workflow

jobs:
  fetch-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Call GitHub API
        id: apicall
        run: |
          # Fetch latest GitHub Actions runner release info
          response=$(curl -s https://api.github.com/repos/actions/runner/releases/latest)
          echo "Full API Response:"
          echo "$response"
          
          # Extract the release tag (like v2.320.0) using jq
          version=$(echo "$response" | jq -r '.tag_name')
          
          # Store the value so next step can use it
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Step 2 - Use the API data
        run: echo "✅ The latest GitHub Actions Runner version is ${{ steps.apicall.outputs.version }}"
