name: Simple CI Workflow

on:
  push:
  

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple script
        run: echo "Hello, this is a simple workflow running at $(date)"

      - name: Push metric to Prometheus
        run: |
          cat <<EOF | curl --data-binary @- http://13.233.214.176:9091/metrics/job/github_actions
         
          workflow_run_total 1
          EOF
